### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by AppleMinerHD** [SalmonGER/StatsPE#10]
Hello ist's me xD Also ich habe gesehen du hast ziemlich viel an der MySQL geschraubt die Dateien werden auch erstellt auf dem MySQL aber wenn ich ingame /stats mache passiert leider nichts

**Comment by SalmonDE** [comment]
Jap, ich muss leider noch daran arbeiten

**Comment by AppleMinerHD** [comment]
Okay danke ich bin dir echt dankbar das ist das einzigste das uns noch fehlt und die anderen Stats Plugins sind ned so das wahrste aber deins ist echt schon hammer mit MySQL is es Ultra für Netzwerke

**Comment by AppleMinerHD** [comment]
Denkst du, du schaffst es heute ?

**Comment by SalmonDE** [comment]
@AppleMinerHD Ich werde wohl in die Nacht reinarbeiten müssen. :D

**Comment by Aericio** [comment]
Offiziell Telegram Gruppe: https://telegram.me/joinchat/Ca8L9T4Wd5GIqZm_yC272w
Schneller kontakt mit uns :)

**Comment by SalmonDE** [comment]
@AppleMinerHD Entschuldigung, ich muss das ganze leider noch einmal verschieben, der spontane Besuch gibt immer noch nicht Ruhe. Aber ich bin zuversichtlich, dass ich heute Abend eventuell noch Zeit finden könnte. 
Nebenbei, Aericio dort oben hat wahrscheinlich einen Übersetzer benutzt, er spricht ja nornalerweise kein Deutsch. :D

**Comment by AppleMinerHD** [comment]
Okay das heisst wan wird MySQL voraussichtlich in etwa Verfügbar sein? :) sorry musste Arbeiten und habe keine Zeig gefunden zu schreiben.

**Comment by SwagGermany** [comment]
Würde mich auch interessieren.

**Comment by AppleMinerHD** [comment]
Aber kann auch verstehen wenn er grad keine Zeit hat er hat auch ein Leben..

**Comment by SwagGermany** [comment]
Ja stimmt ;D

**Comment by SalmonDE** [comment]
@AppleMinerHD Trotzdem ist die Frage natürlich berechtigt. ;) Ich vermute, dass ich es bis zum Ende der Woche fertig kriegen sollte.

**Comment by AppleMinerHD** [comment]
Cool danke für die Auskunft! Bitte behalte das RL trotzdem auf 1. Stelle das Scripten ist ein schönes & Interessantes Hobby! Zuerst DU dann das Scripten :) Gute Nacht! Musste ich grad sagen sry ^^

**Comment by AppleMinerHD** [comment]
Cool etwas mit SaveData wurde implementiert _-_

**Comment by SalmonDE** [comment]
@AppleMinerHD Ist momentan aber auch noch unfertig. Jedoch hat es bei mir schon einige Daten auf meiner Datenbank speichern können. Ich versuche nun dies für alles weitere zu benutzen

**Comment by AppleMinerHD** [comment]
Thx für die Auskunft m8

**Comment by SalmonDE** [comment]
@AppleMinerHD Noch irgendwelche Wünsche? :D
Falls nicht, werde ich nun wohl anfangen am "language_update" zu arbeiten. :)

**Comment by AppleMinerHD** [comment]
Also ist MySQL Implementiert ? Wenn ja nur ein Tipp ändre die Readme datei :D Danke für die Tolle arbeit! Werde gleich noch so nen bestimmten link suchen :)

**Comment by SalmonDE** [comment]
@AppleMinerHD Werde ich machen, danke für die Anmerkung! :)

**Comment by Aericio** [comment]
^^ I guess you want tags now

**Comment by SalmonDE** [comment]
Actually that was a bug report :D

**Comment by Aericio** [comment]
I pressed wrong button lol
