### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by AppleMinerHD** [SalmonGER/StatsPE#12]
![image](https://cloud.githubusercontent.com/assets/17070987/17947363/a790b816-6a4c-11e6-9022-a5ee8c6d5a59.jpg)
Diese meldung kommt wenn ich /stats mache in der MySQL kommen zwar alle Infos aber auf dem Server nur diese Fehlermeldung...

**Comment by AppleMinerHD** [comment]
Server thread/CRITICAL Exception: "Serialization of 'Closure' is not allowed" (EXCEPTION) in "/StatsPE-master/src/StatsPE/Tasks/ShowStatsTask" at line 15

**Comment by SalmonDE** [comment]
Ich vermute mal ein Problem zwischen der Inkompatibilität von ClearSky und Genisys. Ich versuche einen anderen Weg dafür zu finden.
