### ISSUE TITLE
Ganzer server Crasht

### ISSUE THREAD

**Issue by AppleMinerHD** [SalmonGER/StatsPE#13]
Genisys Crash Dump Wed Aug 24 21:39:34 UTC 2016

Error: Argument 1 passed to pocketmine\Server::getPlayerExact() must be of the type string, null given, called in /home/minecraft/multicraft/servers/server1566/plugins/StatsPE-master/src/StatsPE/Tasks/ShowStatsTask.php on line 41
File: /src/pocketmine/Server
Line: 1084
Type: notice

Code:
[1075] 
[1076]      return $found;
[1077]  }
[1078] 
[1079]  /**
[1080]   \* @param string $name
[1081]   *
[1082]   \* @return Player
[1083]   */
[1084]  public function getPlayerExact(string $name){
[1085]      $name = strtolower($name);
[1086]      foreach($this->getOnlinePlayers() as $player){
[1087]          if(strtolower($player->getName()) === $name){
[1088]              return $player;
[1089]          }
[1090]      }
[1091] 
[1092]      return null;
[1093]  }
[1094] 

Backtrace:
#0 /src/pocketmine/scheduler/AsyncPool(151): StatsPE\Tasks\ShowStatsTask->onCompletion(pocketmine\Server object)
#1 /src/pocketmine/scheduler/ServerScheduler(268): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#2 /src/pocketmine/Server(2970): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 1063)
#3 /src/pocketmine/Server(2668): pocketmine\Server->tick(boolean)
#4 /src/pocketmine/Server(2546): pocketmine\Server->tickProcessor(boolean)
#5 /src/pocketmine/Server(2111): pocketmine\Server->start(boolean)
#6 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/genisys_PHP7.phar/, string /home/minecraft/multicraft/servers/server1566/, string /home/minecraft/multicraft/servers/server1566/plugins/, string unknown)
#7 (1): require_once(string phar:///home/minecraft/multicraft/jar/genisys_PHP7.phar/src/pocketmine/PocketMine.php)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
uname -a: Linux mc12 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 54 seconds
Number of loaded worlds: 1
Players online: 1/50

Loaded plugins:
AdvancedMOTD 1.0.1 by Philip Shilling for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
Friends 1 by Bluplayz for API(s) 1.14.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
RandomNick 1 by UltimateDevs for API(s) 2.0.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
VersionModifier 1.0.0 by applqpak, keithkfng for API(s) 1.0.0, 2.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
AMHD 1.0.0 by AppleMinerHD for API(s) 1.10.0
ZMusicBox 1 by ondraczsk for API(s) 1.0.0
SynapseTransfer 1.0.0 by iTX Technologies for API(s) 2.0.0
Server 1.0.0 by AppleMinerHD for API(s) 1.10.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
StatsPE 2.0.0 by SalmonDE, SalmonDE, Aericio for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

**Comment by SalmonDE** [comment]
Kleiner Logik Fehler. :D
Muss jetzt aber noch einen anderen beheben.

**Comment by SalmonDE** [comment]
@AppleMinerHD Sollte gefixt sein. Entschuldige, dass es länger gedauert hat als gedacht. :/
Download: https://github.com/SalmonGER/StatsPE/releases/latest/

**Comment by ghost** [comment]
@AppleMinerHD Speak english?

**Comment by Aericio** [comment]
@NycuRO Why? Salmon knows German so its fine. (i thought we don't really support genisys?)

**Comment by robske110** [comment]
@NycuRO Has made a good (dfuc i'm sayin') point here... English should be the main lang.

**Comment by SalmonDE** [comment]
@robske110 I was feeling like he wouldn't give me enough information if we talk in English, but yeah, English should be really the main language
