### ISSUE TITLE
Floatingstats

### ISSUE THREAD

**Issue by AppleMinerHD** [SalmonGER/StatsPE#17]
Bei mir ist da nur ein T in der Luft is das normal? xD

**Comment by SalmonDE** [comment]
Du benutzt wahrscheinlich die eine Testversion. :D

FloatingStats sind momentan nur für JSON Benutzer verfügbar:
![image](https://cloud.githubusercontent.com/assets/15953947/17982636/008ce8b0-6b09-11e6-8f84-b0813a04e991.png)
Ich arbeite jetzt daran, es auch für MySQL Nutzer verfügbar zu machen.

**Comment by AppleMinerHD** [comment]
Wann is es fertig :(

**Comment by SalmonDE** [comment]
@AppleMinerHD Ich hoffe mal noch heute. :)

**Comment by AppleMinerHD** [comment]
kk :( hoffe ich auch

**Comment by SalmonDE** [comment]
@AppleMinerHD [21:36:50] [Server thread/CRITICAL]: [StatsPE] Konnte keine erfolgreiche Verbindung zur MySQL Datenbank herstellen: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.

Das macht mir momentan Probleme, liegt aber wohl an meinem MySQL Server. Werde ihn mal neustarten,
