### ISSUE TITLE
error enter player

### ISSUE THREAD

**Issue by NycuR0** [SalmonGER/StatsPE#31]
### General

**Server Software** I use: Apollo akka Genisys

**Version** of StatsPE I use: latest

**Data Provider** I use: [] MySQL, [] JSON
JSON
## Steps to reproduce the issue

Enter one player in server ( new player config to StatsPE ) and get error:

Warning: file_get_contents(/root/temp/plugins/StatsPE/Stats/ianismegapvp.json): failed to open stream: No such file or directory in /root/temp/plugins/StatsPE-master CODE/src/SalmonDE/StatsPE.php on line 340

**Comment by SalmonDE** [comment]
Can't reproduce hmm, can you give me the Version String?

**Comment by NycuR0** [comment]
version : 2.3.5

If you add plugin for first time and server is whitelist and other players enter ,get error . ( create new file .json )

**Comment by NycuR0** [comment]
In spawn is added FlotingStats. If one player is new and enter, get error.

**Comment by SalmonDE** [comment]
Oh, a floating stat? will try that.

**Comment by SalmonDE** [comment]
Still can't reproduce. File is being created just fine for me.

**Comment by ghost** [comment]
NO. 
Error is creating file .yml in Stats folder.

**Comment by SalmonDE** [comment]
Try restarting the server, or creating a folder called "Stats" inside the plugins folder

**Comment by ghost** [comment]
:/

**Comment by ghost** [comment]
Close issue.
