### ISSUE TITLE
MD5 hash was incorrect

### ISSUE THREAD

**Issue by ClockProgramming** [SalmonGER/StatsPE#34]
#### **Server Software:**
- [ ] Pocketmine-MP
- [x] Genisys
- [ ] ClearSky
- [ ] ImagicalMine
- [ ] Other: (Software)
#### **Version of StatsPE:**
- [x] 2.3.7
#### **Data Provider:**
- [ ] MySQL 
- [x] JSON
#### **Steps to Reproduce the Issue**
1. Start the server
2. Wait or the statsPE to update himself
3. MD5 hash was incorrect

**Comment by SalmonDE** [comment]
Could you try manually updating and tell us if this still occurs on the next update?

**Comment by ClockProgramming** [comment]
ok

**Comment by Aericio** [comment]
Does it still occur?

**Comment by ClockProgramming** [comment]
Idk, I download the new update. So I haven't reproduced it

**Comment by robske110** [comment]
ok, so this seems to be fixed

**Comment by daniktheboss** [comment]
Fixed. Has this for 3 days.

**Comment by ClockProgramming** [comment]
Yup fixed. But the weird is. When I started my server an hour ago. It checks for an update but no update found.

But when I checked the repo and noticed some update 5 hrs ago. I realised this.
Also, can the plugin just use the reload command instead of stopping it?

**Comment by SalmonDE** [comment]
@GlitchPlayer It should also use the /reload command since the plugin checks for an update onEnable which is also triggered by a reload. :)
The Auto Updater only updates StatsPE if the version was changed in plugin.yml. 

This is to prevent updating to not stable versions which are in testing.

**Comment by Aericio** [comment]
Also auto-updaters effect startup speed >:)

**Comment by SalmonGER** [comment]
@Aericio How? It doesn't for me

**Comment by Aericio** [comment]
oh i still got old af version
