### ISSUE TITLE
OnlineTime

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#36]
#### **Server Software:**
- [ ] Pocketmine-MP
- [x] Genisys
- [ ] ClearSky
- [ ] ImagicalMine
- [ ] Other: (Software)
###### Do /version StatsPE to check

Latest man .
#### **Data Provider:**
- [ ] MySQL 
- [x] JSON
#### **Steps to Reproduce the Issue**
1. Enter on server
2. Watch floatingstats
#### **Extra Information**

All have OnlineTime 21h 23 min and 9 seconds. Why? Please create task for floatingstats for fix this problem.

**Comment by NycuRO** [comment]
@SalmonGER

**Comment by RocoWayne** [comment]
in pocketmine it loads, create the folder but dont save any stats :(

**Comment by SalmonDE** [comment]
@RocoWayne Any errors or more information?

**Comment by SalmonDE** [comment]
@NycuRO I actually want to redo that. It's quite buggy

**Comment by RocoWayne** [comment]
Not one error @SalmonGER, the plugin load just fine, create the config folder with all the files, but whe i play dont save anything. In the logs i dont see anything wrong

**Comment by SalmonDE** [comment]
@RocoWayne What version of PocketMine do you use? I'll try to reproduce

**Comment by RocoWayne** [comment]
is a custom, i cant release it yet :/

**Comment by robske110** [comment]
THERE IS NO FUCKING NEED TO CREATE A TASK
playerJoinEvent & playerQuitEvent are enough

**Comment by ghost** [comment]
@robske110 You can create task for floatingstats for add live OnlineTime . For no need enter and quit ;) 
More like that and is more useful ;)

**Comment by Aericio** [comment]
Whatever Nyco recommends = creates more lag.

**Comment by NycuRO** [comment]
@Aericio No create lag,lol :))

**Comment by Aericio** [comment]
Stop being lazy and just do /stats.
