### ISSUE TITLE
Typo in every language file

### ISSUE THREAD

**Issue by SalmonDE** [SalmonGER/StatsPE#37]
### **_General**_

CreateTableSucces should be CreateTableSuccess (A "s" is missing)
#### **Server Software:**
- [ ] Pocketmine-MP
- [ ] Genisys
- [ ] ClearSky
- [ ] ImagicalMine
- [ ] Other: (Software)
- [x] not related
#### **Version of StatsPE:**

2.4.4
#### **Data Provider:**
- [x] MySQL 
- [ ] JSON

**Comment by Aericio** [comment]
Understood.

**Comment by Aericio** [comment]
MySQL?

**Comment by SalmonDE** [comment]
It should be in the MySQL section of the language files @Aericio

**Comment by Aericio** [comment]
Oh, lol.
