### ISSUE TITLE
FloatingStats

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#38]
#### **Server Software:**
- [ ] Pocketmine-MP
- [x] Genisys // FUCKING USE `x` NOT `*` ASSHOLE~ a nycuro hater
- [ ] ClearSky
- [ ] ImagicalMine
- [ ] Other: (Software)
###### Do /version StatsPE to check

latest man
#### **Data Provider:**
- [ ] MySQL 
- [x] JSON
#### **Steps to Reproduce the Issue**
1. Enter on server
2. create floatingstats
3. watch
#### *_Extra Information_

Default lang (eng) is set in floatingstats , not lang is set in config.yml if i'm creating /floatingstats add {player}

And sometimes it get bug and killings and more and they look .. @SalmonGER 
For fix need add to floatingstats : Name '{player}' because if you used /floatingstats add {player} is not added name: '{player}'

**Comment by Aericio** [comment]
Provide picture, I don't understand your English.

**Comment by Aericio** [comment]
@NycuRO Provide a picture or learn proper English.
