### ISSUE TITLE
Undefined constant in $info array

### ISSUE THREAD

**Issue by SalmonDE** [SalmonGER/StatsPE#4]
Perhaps getStats() contains the issue

Notice: Use of undefined constant PlayerName - assumed 'PlayerName' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 86

Notice: Use of undefined constant ClientID - assumed 'ClientID' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 88

Notice: Use of undefined constant LastIP - assumed 'LastIP' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 89

Notice: Use of undefined constant FirstJoin - assumed 'FirstJoin' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 91

Notice: Use of undefined constant LastJoin - assumed 'LastJoin' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 92

Notice: Use of undefined constant JoinCount - assumed 'JoinCount' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 93

Notice: Use of undefined constant KillCount - assumed 'KillCount' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 94

Notice: Use of undefined constant DeathCount - assumed 'DeathCount' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 95

Notice: Use of undefined constant KickCount - assumed 'KickCount' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 96

Notice: Use of undefined constant OnlineTime - assumed 'OnlineTime' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 97

Notice: Use of undefined constant BlocksBreaked - assumed 'BlocksBreaked' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 98

Notice: Use of undefined constant BlocksPlaced - assumed 'BlocksPlaced' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 99

Notice: Use of undefined constant ChatMessages - assumed 'ChatMessages' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 100

Notice: Use of undefined constant FishCount - assumed 'FishCount' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 101

Notice: Use of undefined constant EnterBedCount - assumed 'EnterBedCount' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 102

Notice: Use of undefined constant EatCount - assumed 'EatCount' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 103

Notice: Use of undefined constant OnlineTime - assumed 'OnlineTime' in phar://C:/Users/garre_000/Desktop/Network/plugins/StatsPE_v0.0.9.phar/src/StatsPE/StatsPE.php on line 104

`

**Comment by Aericio** [comment]
D:

**Comment by SalmonDE** [comment]
I guess the data doesn't get correctly decoded by json_decode

**Comment by SalmonDE** [comment]
array(17) {
  ["PlayerName"]=>
  string(8) "SalmonDE"
  ["ClientID"]=>
  string(20) "-55555555555"
  ["LastIP"]=>
  string(13) "93.228.72.164"
  ["FirstJoin"]=>
  string(19) "03:43:34 22.07.2016"
  ["LastJoin"]=>
  string(19) "03:49:30 22.07.2016"
  ["JoinCount"]=>
  string(1) "5"
  ["KillCount"]=>
  string(1) "0"
  ["DeathCount"]=>
  string(1) "0"
  ["KickCount"]=>
  string(1) "0"
  ["OnlineTime"]=>
  string(3) "WIP"
  ["BlocksBreaked"]=>
  string(1) "0"
  ["BlocksPlaced"]=>
  string(1) "0"
  ["ChatMessages"]=>
  string(1) "0"
  ["FishCount"]=>
  string(1) "0"
  ["EnterBedCount"]=>
  string(1) "0"
  ["EatCount"]=>
  string(1) "0"
  ["CraftCount"]=>
  string(1) "0"
}
