### ISSUE TITLE
The flying text is automatically deleted.

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#42]
#### **Server Software:**
- [ ] Pocketmine-MP
- [x] Tesseract
- [ ] ClearSky
- [ ] ImagicalMine
- [ ] Other: (Software)

#### **Data Provider:**

- [x] MySQL 
- [ ] JSON

#### **Steps to Reproduce the Issue**
1. The flying text is automatically deleted.

**Comment by SalmonDE** [comment]
Do you mind if I ignore this issue for now? I'd like to test this after I finished the rewrite.

**Comment by SalmonDE** [comment]
Possibly fixed in 1890f3a8ba63e78b8ef0646ee15cc436b6763b5b.
Thank you for reporting!
