### ISSUE TITLE
Floating stats show up in all worlds, but only set in one. 

### ISSUE THREAD

**Issue by Leejit** [SalmonGER/StatsPE#44]
#### **Server Software:**
- [ ] PocketMine-MP (PMMP)
- [ ] CSPMMP
- [ ] Genisys
- [X] Tesseract
- [ ] Other: (Software)

#### **Version of StatsPE:**

2.4.7

#### **Data Provider:**

- [ ] MySQL  (I can't even figure this out on my website...)
- [X] JSON

#### **Steps to Reproduce the Issue**
1.

Use Tesseract. setup a floating stat

**Comment by Aericio** [comment]
this is already known "bug", reason why quotations is because i am not sure if its actually a bug.

**Comment by SalmonDE** [comment]
I'll try to add multi world support for it inside the rewrite branch

**Comment by hqn21** [comment]
me too :)
hope u can fix it soon

**Comment by SalmonDE** [comment]
Added and tested in 1890f3a8ba63e78b8ef0646ee15cc436b6763b5b. :)
Thank you for the report!
