### ISSUE TITLE
Online data field?

### ISSUE THREAD

**Issue by k3ithos** [SalmonGER/StatsPE#47]
### ***General***
Before the rewrite there was an 'Online' field which displayed whether the player was online or not. As far as I know, it was removed in the rewrite? Can this be reimplemented?

#### **Server Software:**
- [ ] PocketMine-MP (PMMP)
- [ ] CSPMMP
- [ ] Genisys
- [ ] Tesseract
- [x] Other: (Software)
Custom, fork of Tesseract

#### **Version of StatsPE:**

Latest as of https://github.com/SalmonDE/StatsPE/commit/aaf1479801ee8f40c0407df075dec802ac1632ce

#### **Data Provider:**

- [x] MySQL 
- [ ] JSON

**Comment by SalmonDE** [comment]
Sure, my thought was that people could use query to determine what players are online. But I'll add it back again. :)

**Comment by SalmonDE** [comment]
Tested and should be working. 💃 
See if the column get's added for you automatically, it should do so.
