### ISSUE TITLE
Saving First and Last Join fields

### ISSUE THREAD

**Issue by soupdudez** [SalmonGER/StatsPE#48]
### ***General***
Can you add an option to save the first and last join fields to a MySQL database? They are quite useful to calculate the time when the player was last seen to display on a stats website.

#### **Server Software:**
- [ ] PocketMine-MP (PMMP)
- [ ] CSPMMP
- [ ] Genisys
- [x] Tesseract
- [ ] Other: (Software)

#### **Version of StatsPE:**

Latest commit, https://github.com/SalmonDE/StatsPE/commit/f81dd19c610d5763ee43565129f4c6d538fc1fe6

#### **Data Provider:**

- [x] MySQL 
- [ ] JSON

#### **Steps to Reproduce the Issue**
1.

**Comment by SalmonDE** [comment]
Yes that was also in my mind, I just had a problem which is solved now. I'll add it as soon as I wake up. :)

**Comment by SalmonDE** [comment]
Added in: 82ac544b30892becb4bb69a0aee0cd1efe78b2cd
Remember, the LastJoin and FirstJoin values do not contain a date but an unix timestamp.
