### ISSUE TITLE
cannot create a floating text

### ISSUE THREAD

**Issue by dries-c** [SalmonGER/StatsPE#49]
#### **General**

```
CRITICAL> Unhandled exception executing command 'statspe floatingtext add henk' in statspe: Argument 1 passed to SalmonDE\StatsPE\Utils::getKD() must be of the type integer, null given, called in phar:///Users/Ronny/Desktop/GameCraft PE 1.0.3!/Hub/plugins/StatsPE.phar/src/SalmonDE/StatsPE/FloatingTexts/FloatingText.php on line 55
[Tesseract] [14:07:05] CRITICAL> TypeError: "Argument 1 passed to SalmonDE\StatsPE\Utils::getKD() must be of the type integer, null given, called in phar:///Users/Ronny/Desktop/GameCraft PE 1.0.3!/Hub/plugins/StatsPE.phar/src/SalmonDE/StatsPE/FloatingTexts/FloatingText.php on line 55" (EXCEPTION) in "/plugins/StatsPE.phar/src/SalmonDE/StatsPE/Utils" at line 26
```

#### **Server Software:**

Tesseract

#### **Version of StatsPE:**

latest build

#### **Data Provider:**

- [ ] MySQL
- [x] JSON

#### **Steps to Reproduce the Issue**

1.create a floating text

#### **Extra Information**

CRITICAL> Unhandled exception executing command 'statspe floatingtext add henk' in statspe: Argument 1 passed to SalmonDE\StatsPE\Utils::getKD() must be of the type integer, null given, called in phar:///Users/Ronny/Desktop/GameCraft PE 1.0.3!/Hub/plugins/StatsPE.phar/src/SalmonDE/StatsPE/FloatingTexts/FloatingText.php on line 55
[Tesseract] [14:07:05] CRITICAL> TypeError: "Argument 1 passed to SalmonDE\StatsPE\Utils::getKD() must be of the type integer, null given, called in phar:///Users/Ronny/Desktop/GameCraft PE 1.0.3!/Hub/plugins/StatsPE.phar/src/SalmonDE/StatsPE/FloatingTexts/FloatingText.php on line 55" (EXCEPTION) in "/plugins/StatsPE.phar/src/SalmonDE/StatsPE/Utils" at line 26

**Comment by SalmonDE** [comment]
Interesting, it returned null as KillCount. Sorry but could you look inside your json file and search for the null value?

**Comment by dries-c** [comment]
it was the fist time i used it so i dont have files there expect playing
count and date

Op 4-apr.-2017 17:39 schreef "SalmonDE" <notifications@github.com>:

**Comment by SalmonDE** [comment]
@Driesboy It still should've saved 0 as KillCount, not null

**Comment by dries-c** [comment]
What do i need to do to fix it

Op 4-apr.-2017 18:35 schreef "SalmonDE" <notifications@github.com>:

**Comment by SalmonDE** [comment]
Could you test it again, please?

**Comment by SalmonDE** [comment]
What I can think of is that KillCount wasn't enabled. If it would be enabled and null was saved it should've put an error of it saying that an unexpected datatype was given (null instead of integer).

This would also prevent it to overwrite the value, which seemed to be the case for you at the first look. But I think DeathCount just isn't set so of course it returns null.

(Sleepy thoughts written in my bed, Sleepy thoughts fixed by Aericio)

**Comment by SalmonDE** [comment]
Any news relating to this issue @Driesboy ?

**Comment by SalmonDE** [comment]
I will close this now because it seems like there isn't any interest in this issue anymore or it perhaps already is solved. If I'm wrong let me know, I will then reopen it.

**Comment by dries-c** [comment]
sorry i was on vacance

**Comment by dries-c** [comment]
will test it tomorrow

**Comment by dries-c** [comment]
works thx
