### ISSUE TITLE
How to use the MySQL?

### ISSUE THREAD

**Issue by PluginBOXone** [SalmonGER/StatsPE#50]
#### **General**
How can I use the MySQL in StatsPE? I know that you can set it in the Config. but what do I have to fill in correctly? I am useing Debian 8

#### **Server Software:**
Tesseract / Debian 8 

#### **Version of StatsPE:**
Newest Version

**Comment by SalmonDE** [comment]
It actually says that in the README file with links to the config lines, look there if my linkless description isn't enough.

First you'll want to put your credentials inside the MySQL block **at the bottom of the config** together with the database name and the host address.
After that you have to set mysql as your data provider a few lines above the mysql block. **Replace json** with **mysql**

**Comment by Aericio** [comment]
In order to use MySQL, you need `mysql-server` OR `mariadb-server`  (do not have both!) installed on your Linux system. Assuming you have that all setup already, all you need to do is what @SalmonDE said above.

**Comment by PluginBOXone** [comment]
Ok thx!

**Comment by PluginBOXone** [comment]
I have got now MySQL with phpMyAdmin and all this stuff... but when i am trying to connect the plugin says this; [StatsPE] Error while connecting to the MySQL server: (2002)
                [StatsPE] Connection refused

**Comment by SalmonDE** [comment]
@PluginBOXone That error should be coming from the mysql server. Please check your configuration, is the server online? Do you use the right port? Is the hostname correct?

**Comment by Aericio** [comment]
If MySQL was setup for localhost connection (via unix socket), I suggest you put "0.0.0.0" in the hostname line instead of your public ip. To check if MySQL is online, login to PMA and open some tables. If it works, that should mean MySQL server is up. You could also do `/etc/init.d/mysql status` (i think lol) to check if its running via command line.
