### ISSUE TITLE
Error that stops Server!

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#51]
#### **General**
When I begin my server it all goes well until it loads StatsPE then it crashes instantly!

#### **Server Software:**
Currently, I am using [Tesseract](https://github.com/TesseractTeam/Tesseract)

#### **Version of StatsPE:**
My StatsPE vesison is 3.2.6

#### **Data Provider:**

Currently I am saving my Data with JSON

#### **Steps to Reproduce the Issue**

1. Install Tesseract
2. Inside tesseract.yml make sue folder plugin loading is set to **true**
3. Insert the Plugin into the /plugins folder (not a phar)
4. Bump the API to 3.0.1
5. Run the Server
6. Watch the errors come
7. The server will crash!

#### **Extra Information**

`CRITICAL> Error: "Call to undefined method SalmonDE\StatsPE\Base::runUpdateManager()" (EXCEPTION) in "/StatsPE-master/src/SalmonDE/StatsPE/Base" at line 27`

This is the Tesseract phar that I am using!

 https://47-73522113-gh.circle-artifacts.com/0/tmp/circle-artifacts.MgukxFu/Tesseract_1.2.0.phar

**Comment by ghost** [comment]
Merge [this](https://github.com/SalmonDE/StatsPE/pull/53) to fix the error, i tested it!

**Comment by SalmonDE** [comment]
@NFGamerMC This actually doesn't fix it, but it is a valid workaround. Can you try downloading a phar from [here](https://github.com/SalmonDE/StatsPE/releases/latest)? I believe your StatsPE copy was modified or somehow lost that function.

I also say this because as far as I know and tested this plugin is Tesseract compatible.

**Comment by ghost** [comment]
Okay, as a dev of Tesseract we have been having lots of errors in almost everything since we added RP support!

**Comment by SalmonDE** [comment]
Was this issue fixed for you after redownloading StatsPE? @NFGamerMC

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/25032317/bb45e27c-206e-11e7-931c-48112dbf78de.png)
seems to be your own problem, its fine for me.
