### ISSUE TITLE
MySQL Optimization

### ISSUE THREAD

**Issue by SalmonDE** [SalmonGER/StatsPE#56]
To prevent blocking the main thread, I'd like to send queries with an async task.

Edit:
@SleepSpace9's suggestion to add a "cache" for changes and a configuration to set the limit of changes in memory is going to be implemented, too.

**Comment by SleepSpace9** [comment]
Maybe you can avoid a lot of reads/writes from/to data provider when you only do it at PlayerJoin and PlayerQuit. So ...
- read player's stats data from data provider on join, 
- update and work with the data in memory while he's online 
- and write it back to data provider only when he quits the server or on server shutdown

Of course reading and writing to the data provider should be done asynchronously.

This will increase the risk that some data will be lost if the server stops unnormally, but I think the performance gain is more important.

**Comment by SalmonDE** [comment]
@SleepSpace9 This is a good thought, but sometimes you want live statistics in a database which then possibly also show up on a website.
If you talk about json however, the plugin currently only saves the data on disable.

**Comment by SleepSpace9** [comment]
I didn't think of live statistics, then you probably have no choice doing it another way, maybe only write in an acceptable interval. I mainly thought about MySQL and saw that e.g. every block break would trigger a write to the database. This scared me a little bit 😉 .

**Comment by SalmonDE** [comment]
@SleepSpace9 Yup, I also thought of a configurable cache limit but then ditched it.
This sounds nice, a given amount of changes which then triggers an async query to the mysql database. Do you agree or do you have further suggestions?

**Comment by SleepSpace9** [comment]
👍 sounds good!
