### ISSUE TITLE
Floatingtext add Command

### ISSUE THREAD

**Issue by EtchReborn** [SalmonGER/StatsPE#58]
#### **General**
When i use the command /statspe floatingtext add (myname) it dosent do anything it just says the error command message... But when i use other commands from statspe plugin it works

#### **Server Software:**
Clearsky 1.0.7

#### **Version of StatsPE:**
3.4.4

#### **Data Provider:**

- [ ] MySQL
- [x] JSON

**Comment by SalmonDE** [comment]
Is there an error printed out in the console after using the command?

**Comment by EtchReborn** [comment]
No theres not

**Comment by SalmonDE** [comment]
Really? Can you send me a screenshot and which version of ClearSky you're exactly using?

**Comment by EtchReborn** [comment]
![screenshot_2017-05-15-21-56-36](https://cloud.githubusercontent.com/assets/28599276/26076666/c773b34e-39b9-11e7-834a-7690da40b9c2.png)

**Comment by EtchReborn** [comment]
![screenshot_2017-05-15-22-01-40](https://cloud.githubusercontent.com/assets/28599276/26076782/37002c6a-39ba-11e7-9ca9-f43922cbb9e6.png)
![screenshot_2017-05-15-22-01-12](https://cloud.githubusercontent.com/assets/28599276/26076791/3cd5e03a-39ba-11e7-8b06-23d2daa10a9f.png)

**Comment by SalmonDE** [comment]
As of [this](https://github.com/pmmp/PocketMine-MP/blob/653b6b55a9ab44d24e9402d0a253b3d394c62908/src/pocketmine/command/SimpleCommandMap.php#L220) there has to be an error printed to the console. I'm going to either need this error message or the **exact** version of ClearSky you're using.

The screenshot you've provided me unfortunately does not reveal the version of ClearSky on your server.
Don't get me wrong, I'd be glad to fix this error but I need information to do so.

**Comment by Matthww** [comment]
There is a typo on line 60 in Floating Text manager

**Comment by SalmonDE** [comment]
Thanks! @Matthww
Was this the cause of this issue?

**Comment by EtchReborn** [comment]
:O

**Comment by EtchReborn** [comment]
Lemme try it now

**Comment by EtchReborn** [comment]
It works

**Comment by EtchReborn** [comment]
The problem is solved

**Comment by Matthww** [comment]
:) Also @SalmonDE Why aren't floatingtext not updating?

And you should add a floating text showing people with the most kills

**Comment by SalmonDE** [comment]
@Matthww Updating the floatingtext as soon as a statistic changes? I could add that with a switch inside the config file.

Your second suggestions is supposed to be added in ServerStats. (An extension for StatsPE I'm planning to code) :)

Also, could you open an own issue for your first suggestion?
