### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#59]
#### **General**

when i do /stats (player) i get this error and the stats don't show up
#### **Server Software:**

GenisysPro
#### **Version of StatsPE:**

3.4.4
#### **Data Provider:**

- [ ] MySQL
- [. ] JSON <--

#### **Steps to Reproduce the Issue**

1. no idea

#### **Extra Information**

 
Server thread/ERROR]: [StatsPE] Unexpected datatype returned "NULL" for entry "ChatCount" in "SalmonDE\StatsPE\Providers\JSONProvider" by "getData"! 

----------
and this one occurred for no reason:

Notice: Undefined index: JoinCount in phar:///plugins/StatsPE (1).phar/src/SalmonDE/StatsPE/EventListener.php on line 14

**Comment by SalmonDE** [comment]
Can you check if there are any null values inside your players.yml file?

**Comment by ghost** [comment]
i double checked . there was non
