### ISSUE TITLE
uhm....

### ISSUE THREAD

**Issue by Leejit** [SalmonGER/StatsPE#6]
Getting all this info, wouldn't it cause a lot of lag ??

**Comment by Aericio** [comment]
It wont cause a lot of lag, no worries. If you want to check yourself, do /timings :)
Since it is in .json, it's faster. These type plugins don't cause a lot of lag anyways.

**Comment by SalmonDE** [comment]
I tried to keep the code more simple. And my experience tells me it doesn't lag. Well, tell me if it does or you encounter any other issues. :)

**Comment by Aericio** [comment]
> I tried to keep the code more simple. And my experience tells me it doesn't lag. Well, tell me if it does or you encounter any other issues. :)

To add-on, make sure it isn't some other plugin causing lag. As I said, do /timings to make sure its actually StatsPE. :)

**Comment by Aericio** [comment]
Allllllthough... the auto-updater does effect startup time when Salmon's website is offline.

**Comment by SalmonDE** [comment]
Yup, I should make that deactivable too. Could also be fixed by checking asyncly for an update, but that would take an async thread away which could be used by something else

**Comment by SalmonDE** [comment]
Forget that, just learned something new lol. @aericio can you add "Async Update check" to the ToDo List?

**Comment by Aericio** [comment]
Okay.
