### ISSUE TITLE
3.4.5 update

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#60]
#### **General**

i just downloaded the last src from master and this error showed up on server start
#### **Server Software:**

GenisysPro
#### **Version of StatsPE:**

3.4.5
#### **Data Provider:**

- [ ] MySQL
- [  ] JSON  <----

#### **Steps to Reproduce the Issue**

1. download the last src and start the server

#### **Extra Information**

Server thread/INFO]: Enabling StatsPE v3.4.5 17.05 18:51:30 [Server] INFO [Server thread/INFO]: [StatsPE] Selecting JSON data provider ... 17.05 18:51:30 [Server] INFO [Server thread/CRITICAL]: ClassNotFoundException: "Class SalmonDE\Updater\UpdateManager not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144 17.05 18:51:30 [Server] INFO [Server thread/INFO]: Disabling StatsPE v3.4.5

**Comment by SalmonDE** [comment]
Please download the plugin from [here](https://github.com/SalmonDE/StatsPE/releases)
