### ISSUE TITLE
Possibly broken online time

### ISSUE THREAD

**Issue by SalmonDE** [SalmonGER/StatsPE#62]
#### **General**

Onlinetime could be broken, I didn't test it for sure yet

#### **Server Software:**

PMMP master branch

#### **Version of StatsPE:**

3.5.2

#### **Data Provider:**

MySQL

#### **Steps to Reproduce the Issue**

Cannot provide steps yet

#### **Extra Information**

It seems like online time stays at around 4 minutes. But it could be the old online time which couldn't be increased after an update.

**Comment by SalmonDE** [comment]
Could be related to 1b4d0b95ac457524ae50c29c866366b758505c74

**Comment by ghost** [comment]
@SalmonDE FloatingText Particle on time real (live) ? (K/D)
