### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OfficialLilKev** [SalmonGER/StatsPE#64]
#### **General**
 Username Error

#### **Server Software:**
 Tesseract

#### **Version of StatsPE:**
 3.5.2

#### **Data Provider:**
 
- [ ] MySQL
- [x] JSON

#### **Steps to Reproduce the Issue**

1. just do /stats ingame

#### **Extra Information**

28.06 00:54:00 [Server] INFO /04:54:00 [CRITICAL] ErrorException: "Undefined index: Username" (EXCEPTION) in "/StatsPE-master/src/SalmonDE/StatsPE/Commands/StatsCmd" at line 27 28.06 00:54:00 [Server] INFO /04:54:00 [CRITICAL] Unhandled exception executing command 'stats BajanAmerican' in stats: Undefined index: Username

**Comment by Aericio** [comment]
Please use pmmp to test this issue. If it is a problem that occurs with pmmp also, we will look into it. (we, as in @SalmonDE)

**Comment by Aericio** [comment]
Closing issue- insufficient information.
