### ISSUE TITLE
Update? API?

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#72]
This plugin have Api?

Can you update for pmmp alpha9?

Thx salami :3 @SalmonDE 

btw, how are you?

**Comment by ghost** [comment]
@SalmonDE Salami! Why you bastard!

**Comment by SalmonDE** [comment]
I updated the plugin to the api version 3.0.0-ALPHA9. Why do you call me bastard?

**Comment by ghost** [comment]
"btw, how are you?" -_-
