### ISSUE TITLE
pmmp have new api, for PING! Add ping and there :d

### ISSUE THREAD

**Issue by ghost** [SalmonGER/StatsPE#75]
Title say all.

Commit: https://github.com/pmmp/PocketMine-MP/commit/fd0b07a0aaa0b761a8b59319e30b61f26060336d

**Comment by Aericio** [comment]
I don't see the reason to add ping of a player.

**Comment by ghost** [comment]
@SalmonDE What do you think?

@Aericio Hello aericio, how are you ? :d And why not, it's one "Stats" plugin 👍

**Comment by SalmonDE** [comment]
I agree with @Aericio. Server to player pings statistics can be added by an external plugin but it isn't needed in statspe itself.

**Comment by ghost** [comment]
@SalmonDE Salami, don't be understood.

**Comment by NycuRO** [comment]
@SalmonDE Salami, don't be understood.

**Comment by NycuRO** [comment]
@SalmonDE Salami, don't be understood.

**Comment by Aericio** [comment]
There is no need for StatsPE to collect this data... besides, the data only updates on a set interval. Sure, @SalmonDE could make it so it retrieves it each time /stats is ran, but I believe this belongs in another plugin. Collecting players ping is not necessary. What would you do with their ping data anyways, seems pretty useless to me.
