### ISSUE TITLE
PLS UPDATE

### ISSUE THREAD

**Issue by Bruhh1234** [SalmonGER/StatsPE#82]
#### **General**
PLS UPDATE

#### **Server Software:**
To the newest Pocketmine-MP 3.15.1

#### **Version of StatsPE:**
Latest

#### **Data Provider:**
- [ x] MySQL
- [x ] JSON

#### **Steps to Reproduce the Issue**
No steps
#### **Extra Information**
Thx man

**Comment by SalmonDE** [comment]
Sorry, this project won't be updated anymore.
