### ISSUE TITLE
Advanced Info & Question

### ISSUE THREAD

**Issue by AppleMinerHD** [SalmonGER/StatsPE#9]
English (Really Bad English):
Why i can't see the advanced Stats of a Player i added the advanced stats Perm to my Rank but it doesen't work. Can you help me?

Question:
Is MySQL supported knwo cause i saw this in the config..?

German:
Ich habe mir die Advanced Stats Permission gegeben aber sehe Trotzdem nicht mehr als mit der Permission. Wissen sie woran das liegen könnte?
Frage: Ist MySQL schon in dieses Plugin mit eingebunden oder steht es einfach nur in der Config weil es kommen wird?

**Comment by SalmonDE** [comment]
Um zuerst das Problem anzusprechen, haben sie sich selbst genau diese Berechtigung erteilt: statspe.cmd.stats.advancedinfo ?

Und nun zur Frage, MySQL ist leider noch nicht ganz eingebunden. Es wurde schon teilweise damit angefangen, aber den Code habe ich irgendwie verloren. Aufjedenfall ist das noch geplant und sollte noch kommen. :)

**Comment by AppleMinerHD** [comment]
Wie kann ich mir die denn erteilen ich habe sie mit PurePerms zur Owner Gruppe hinzuhgefügt..auch die Joins und die K/D kann ich nicht sehen..

**Comment by AppleMinerHD** [comment]
Firstjoin Lastjoin joincount auch nicht ich kann ihnen mal ein Bild senden ..

**Comment by AppleMinerHD** [comment]
![image](https://cloud.githubusercontent.com/assets/17070987/17837311/8657e474-67b0-11e6-9915-d995471bec5b.jpg)
Alles das nicht ausgefüllt ist geht nicht bei mir/uns

**Comment by SalmonDE** [comment]
Irgendwelche Fehlermeldungen in der Konsole? Und können sie mir den Inhalt ihrer .json Datei zeigen?

**Comment by AppleMinerHD** [comment]
Sorry für den ganzen Spamm (Kills geht warscheinlich auch)

**Comment by AppleMinerHD** [comment]
![image](https://cloud.githubusercontent.com/assets/17070987/17837329/f7e0406e-67b0-11e6-9add-30cc644eb058.jpg)

![image](https://cloud.githubusercontent.com/assets/17070987/17837350/54b0d34e-67b1-11e6-9755-0206b12d09f6.jpg)

**Comment by SalmonDE** [comment]
Hmm .. Ich habe schon vermutet, dass das bei gewissen Leuten Probleme machen könnte. Sie benutzen nicht zufälligerweise Genisys?

**Comment by AppleMinerHD** [comment]
xD Doch

**Comment by SalmonDE** [comment]
Sie sollten am besten alle Statistikdateien löschen damit sie fehlerfrei neu erstellt werden können. :)

**Comment by AppleMinerHD** [comment]
Okay Danke vielmals echt Hammer support hier und mal auf Deutsch! Können sie mir noch kurz sagen wann MySQL ungefähr implementiert wird den bei mehereren servern ist das bisschen schade..

**Comment by SalmonDE** [comment]
Ja hmmm ... Ich versuche heute damit weiterzukommen, schließlich will ich einen so lieben Benutzer meines Plugins nicht enttäuschen. :)

**Comment by AppleMinerHD** [comment]
Wissen sie was! Ich liebe sie Jetzt schon. Sie sind so Freundlich und versuchen es uns Recht zu machen. Wenn sie das Plugin Fertig haben bekommen sie zu 100% eine Donation von mir und wenn sie möchten auch irgend einen Rang auf unserem Netzwerk! Danke vielmals.

**Comment by SalmonDE** [comment]
Vielen Dank, aber wenn ich ehrlich bin weiß ich nicht, was ich mit einer Spende anfangen soll, deswegen kann ich das leider nicht annehmen. Den Rang würde ich aber liebend gern haben. :)

**Comment by AppleMinerHD** [comment]
Ah ja genau nochwas bei Online time haben sie ja geschrieben to download wie kann man besser gesagt wo kann man das Downloaden

**Comment by SalmonDE** [comment]
Ach, da haben sie mich ja glatt auf noch einen Fehler aufmerksam gemacht! :)
Es sollte eigentlich To-Do heißen. Ich überlege immer noch, wie ich dies am besten umsetze, ohne den Server unnötig zu belasten.

**Comment by AppleMinerHD** [comment]
Aha okay! Danke für die Antwort :)
